version: "3.4"

services:
    db:
        container_name: projeto_nlw_pg
        image: postgres
        ports:
            - "5431:5431"
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1308
            - POSTGRES_DB=Chat
    app:
        container_name: projeto_nlw_app
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/src/app
        depends_on:
            - db
    pgadmin:
        container_name: projeto_nlw_pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=meutcc@meutcc.com
            - PGADMIN_DEFAULT_PASSWORD=meutcc123
        ports:
            - '5050:80'
        restart: always
        volumes:
            - pgadmin:/root/.pgadmin
        logging:
            driver: none
volumes:
    db-data:
    pgadmin: